[package]
name = "MAC"
version = "0.1.0"
edition = "2021"

[dependencies]
aes="0.7.5"
hex="0.4.3"
block-modes="0.8.1"
hex-literal="0.3.3"
image = "0.24" 
sha1 = "0.10"           
rand = "0.8"
wycheproof = "0.6.0"